import express from "express";
const app = express();

const frases = [
  '"El éxito depende del esfuerzo." - Sófocles',
  '"La vida es lo que pasa mientras estás ocupado haciendo otros planes." - John Lennon',
  '"El conocimiento es poder." - Francis Bacon',
  '"La simplicidad es la máxima sofisticación." - Leonardo da Vinci',
  '"No hay camino para la paz, la paz es el camino." - Mahatma Gandhi',
  '"Sé el cambio que quieres ver en el mundo." - Mahatma Gandhi',
  '"El tiempo es oro." - Benjamin Franklin',
  '"Sólo sé que no sé nada." - Sócrates',
  '"El hombre es la medida de todas las cosas." - Protágoras',
  '"Pienso, luego existo." - René Descartes',
  '"La imaginación es más importante que el conocimiento." - Albert Einstein',
  '"La vida sin música sería un error." - Friedrich Nietzsche',
  '"La felicidad no es algo hecho. Proviene de tus propias acciones." - Dalai Lama',
  '"Lo que no nos mata nos hace más fuertes." - Friedrich Nietzsche',
  '"El que tiene un porqué para vivir puede soportar casi cualquier cómo." - Friedrich Nietzsche',
  '"Haz lo que puedas, con lo que tengas, donde estés." - Theodore Roosevelt',
  '"La mente es todo. Lo que piensas, en eso te conviertes." - Buda',
  '"No es lo que miramos lo que importa, es lo que vemos." - Henry David Thoreau',
  '"La vida es realmente sencilla, pero insistimos en hacerla complicada." - Confucio',
  '"En medio de la dificultad yace la oportunidad." - Albert Einstein',
  '"El que quiere hacer algo encontrará un medio; el que no, encontrará una excusa." - Proverbio árabe',
  '"No hay nada permanente excepto el cambio." - Heráclito',
  '"El conocimiento habla, pero la sabiduría escucha." - Jimi Hendrix',
  '"La mejor manera de predecir el futuro es crearlo." - Peter Drucker',
  '"Nunca consideres el estudio como una obligación, sino como una oportunidad para penetrar en el bello mundo del saber." - Albert Einstein',
  '"Si puedes soñarlo, puedes lograrlo." - Walt Disney',
  '"La paciencia es amarga, pero sus frutos son dulces." - Jean-Jacques Rousseau',
  '"No hay mayor pecado que la pereza." - Thomas Carlyle',
  '"El que no arriesga no gana." - Proverbio',
  '"El coraje no siempre ruge. A veces es la voz tranquila al final del día que dice: \'Lo intentaré de nuevo mañana.\'" - Mary Anne Radmacher',
  '"La educación es el arma más poderosa que puedes usar para cambiar el mundo." - Nelson Mandela',
  '"La mente que se abre a una nueva idea jamás volverá a su tamaño original." - Albert Einstein',
  '"El futuro pertenece a quienes creen en la belleza de sus sueños." - Eleanor Roosevelt',
  '"Quien teme sufrir, sufre ya por lo que teme." - Michel de Montaigne',
  '"El éxito no es definitivo, el fracaso no es fatal: lo que cuenta es el coraje para continuar." - Winston Churchill',
  '"No cuentes los días, haz que los días cuenten." - Muhammad Ali',
  '"El hombre superior es modesto en su hablar, pero excede en sus acciones." - Confucio',
  '"La felicidad depende de nosotros mismos." - Aristóteles',
  '"El arte de la vida consiste en hacer de la vida una obra de arte." - John Ruskin',
  '"No es lo que tienes, ni quién eres, ni dónde estás, ni lo que haces lo que te hace feliz o infeliz. Son solo tus pensamientos." - Dale Carnegie',
  '"La vida es como montar en bicicleta. Para mantener el equilibrio debes seguir adelante." - Albert Einstein',
  '"El hombre valiente no es el que no siente miedo, sino el que conquista ese miedo." - Nelson Mandela',
  '"La medida de la inteligencia es la habilidad de cambiar." - Albert Einstein',
  '"La vida es corta, pero la memoria es larga." - Salvador Dalí',
  '"El éxito consiste en ir de fracaso en fracaso sin perder el entusiasmo." - Winston Churchill',
  '"No esperes. Nunca habrá un momento perfecto." - Napoleon Hill',
  '"Aprende como si fueras a vivir para siempre, vive como si fueras a morir mañana." - Mahatma Gandhi',
  '"Cada día sabemos más y entendemos menos." - Albert Einstein',
  '"El hombre es libre en el momento en que desea serlo." - Voltaire',
  '"La creatividad es la inteligencia divirtiéndose." - Albert Einstein',
  '"Ningún acto de bondad, por pequeño que sea, se desperdicia." - Esopo',
  '"Lo que hacemos en la vida tiene eco en la eternidad." - Máximo, Gladiador',
  '"Nunca dejes que el miedo a perder sea mayor que la emoción de ganar." - Robert Kiyosaki',
  '"El único modo de hacer un gran trabajo es amar lo que haces." - Steve Jobs',
  '"No es la especie más fuerte la que sobrevive, ni la más inteligente, sino la que responde mejor al cambio." - Charles Darwin',
  '"La verdadera sabiduría está en reconocer la propia ignorancia." - Sócrates',
  '"El respeto al derecho ajeno es la paz." - Benito Juárez',
  '"El amor no consiste en mirarse el uno al otro, sino en mirar juntos en la misma dirección." - Antoine de Saint-Exupéry',
  '"La vida es aquello que te sucede mientras estás ocupado haciendo otros planes." - John Lennon',
  '"Los obstáculos son esas cosas espantosas que ves cuando apartas los ojos de tu meta." - Henry Ford',
  '"El que domina a otros es fuerte; el que se domina a sí mismo es poderoso." - Lao Tse',
  '"Lo esencial es invisible a los ojos." - Antoine de Saint-Exupéry',
  '"Si buscas resultados distintos, no hagas siempre lo mismo." - Albert Einstein',
  '"Cree en ti y todo será posible." - Walt Disney',
  '"El éxito no es la clave de la felicidad. La felicidad es la clave del éxito." - Albert Schweitzer',
  '"Nunca es demasiado tarde para ser lo que podrías haber sido." - George Eliot',
  '"Haz de tu vida un sueño, y de tu sueño una realidad." - Antoine de Saint-Exupéry',
  '"La mente es como un paracaídas… solo funciona si se abre." - Albert Einstein',
  '"El que busca un amigo sin defectos se queda sin amigos." - Proverbio turco',
  '"El respeto se gana con los actos, no con las palabras." - Autor desconocido',
  '"El hombre que se levanta es aún más grande que el que no ha caído." - Concepción Arenal',
  '"La educación es el pasaporte hacia el futuro, el mañana pertenece a quienes se preparan hoy." - Malcolm X',
  '"La verdadera felicidad consiste en hacer el bien." - Aristóteles',
  '"Si quieres vivir una vida feliz, átala a una meta, no a personas o cosas." - Albert Einstein',
  '"El mundo es un libro y aquellos que no viajan leen solo una página." - San Agustín',
  '"El secreto de la creatividad es saber cómo esconder tus fuentes." - Albert Einstein',
  '"La verdadera amistad llega cuando el silencio entre dos personas es cómodo." - David Tyson',
  '"La grandeza no consiste en recibir honores, sino en merecerlos." - Aristóteles',
  '"No mires el reloj; haz lo que él hace. Sigue adelante." - Sam Levenson',
  '"El hombre que mueve montañas comienza cargando pequeñas piedras." - Confucio',
  '"La gratitud convierte lo que tenemos en suficiente." - Anónimo',
  '"El conocimiento es la puerta a la libertad." - Epicteto',
  '"Quien controla su ira controla su vida." - Proverbio chino',
  '"No sueñes tu vida, vive tu sueño." - Autor desconocido',
  '"El hombre sabio no dice todo lo que piensa, pero siempre piensa todo lo que dice." - Aristóteles',
  '"Haz que cada día cuente." - Muhammad Ali',
  '"El fracaso es simplemente la oportunidad de comenzar de nuevo, esta vez con más inteligencia." - Henry Ford',
  '"La acción es la llave fundamental de todo éxito." - Pablo Picasso',
  '"El que no sabe es como el que no ve." - Proverbio chino',
  '"Todo lo que somos es el resultado de lo que hemos pensado." - Buda',
  '"Quien tiene paciencia, obtendrá lo que desea." - Proverbio',
  '"Nunca dejes que el miedo decida tu futuro." - Autor desconocido',
  '"El talento gana partidos, pero el trabajo en equipo y la inteligencia gana campeonatos." - Michael Jordan'
];

app.get("/", (req, res) => {
  const random = frases[Math.floor(Math.random() * frases.length)];
  res.send(random); // texto plano con comillas listo para Sketchware
});

const PORT = process.env.PORT || 3000;
app.listen(PORT, () => console.log(`API de frases lista en puerto ${PORT}`));
  
